Driver : Driver.o DoubliLinkedList.o
	g++ -std=c++14 Driver.o DoubliLinkedList.o -o Driver
Driver.o : Driver.cpp DoubliLinkedList.hpp
	g++ -std=c++14 -c Driver.cpp
DoubliLinkedList.o : DoubliLinkedList.cpp DoubliLinkedList.hpp
	g++ -std=c++14 -c DoubliLinkedList.cpp
